spring.application.name=SimpleWebApp
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.auth-expiration=900000
jwt.refresh-expiration=604800000

spring.data.redis.host=localhost
spring.data.redis.port=6379
